Controllers/AlumnosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyFirstProyectWithLineCommand.Models;

namespace MyFirstProyectWithLineCommand.Controllers
{
    public class AlumnosController : Controller
    {
          private readonly ILogger<AlumnosController> _logger;
        public AlumnosController(ILogger<AlumnosController> logger)
        {
             _logger = logger;
        }

       
        public IActionResult AlumnosAdd()
        {
            return View();
        }

        [HttpPost]
         public IActionResult AlumnosAdd(StundetModel alumno)
        {
           if(!ModelState.IsValid)
           {
            _logger.LogWarning("El objeto no es valido");
            return View();
           }

            _logger.LogInformation("El objeto es valido");
         
            return Redirect("studentList");
        }   

        public IActionResult StudentList()
        {
            // Crear objetos de alumnos
            StundetModel alumno = new StundetModel
            {
                Nombre = "Ángel Flores Valdez",
                Carrera = "Ingeniería en sistemas",
                matricula = 44546,
                Edad = 18,
                Sexo = "Masculino"
            };

            StundetModel alumno2 = new StundetModel
            {
                Nombre = "Mario Alberto Loredo",
                Carrera = "Contabilidad",
                matricula = 43722,
                Edad = 18,
                Sexo = "Masculino"
            };

            StundetModel alumno3 = new StundetModel
            {
                Nombre = "Julian Macias Lara",
                Carrera = "Administración de empresas",
                matricula = 44728,
                Edad = 19,
                Sexo = "Masculino"
            };

            // Objetos de lista de alumnos
            List<StundetModel> list = new List<StundetModel>
            {
                alumno,
                alumno2,
                alumno3
            };

            return View(list);
        }

        public IActionResult AlumnosSave()
        {
            // Guardar info
            return Redirect("StudentList");
        }

        public IActionResult AlumnosShowAndEdit(Guid Id)
        {
            StundetModel alumno = new StundetModel();
            
                alumno.Id = Id;
                alumno.Nombre = "Alumno cargado";
            return View(alumno);
        }

        public IActionResult AlumnosEdit(Guid Id)
        {
            StundetModel Alumno=new StundetModel();  
           Alumno.Id=new Guid();
            Alumno.Nombre="Alumno cargado";
            return View(Alumno);
        }

         [HttpPost]
         public IActionResult AlumnosEdit(StundetModel estudiante)
        {
              if(!ModelState.IsValid)
           {
            _logger.LogWarning("El objeto no es valido");
            estudiante.Nombre="Alumno no valido";
            return View(estudiante);
           }

            _logger.LogInformation("El objeto es valido");
         
            return Redirect("StudentList");
        }


        public IActionResult AlumnosShowToDelete(Guid Id)
        {
        StundetModel alumno = new StundetModel();
            
                alumno.Id = Id;
                alumno.Nombre = "Alumno para borrar";
            return View(alumno);
        }

        public IActionResult AlumnosDeleted()
        {
            // Borrar el registro
            return Redirect("StudentList");
        }
    }
}

Controllers/DegreeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyFirstProyectWithLineCommand.Entities;
using MyFirstProyectWithLineCommand.Models;

namespace MyFirstProyectWithLineCommand.Controllers
{
    public class DegreeController : Controller
    {
         private readonly ILogger<DegreeController> _logger;
         private readonly ApplicactionDbContext _context;
        public DegreeController(ApplicactionDbContext context, ILogger<DegreeController> logger)
        {
             _logger = logger;
             _context= context;
        }

        public IActionResult DegreeAdd()
        {
            return View();  
        }   

        
         [HttpPost]
         public IActionResult DegreeAdd(DegreeModel degree)
        {
           if(!ModelState.IsValid)
           {
            _logger.LogWarning("degree.Nombre");
            _logger.LogWarning("El modelo no es valido");
            return View();
           }

            _logger.LogInformation("El objeto es valido");
            Degree degreeBD= new Degree();
            degreeBD.Id=new Guid();
            degreeBD.Name=degree.Nombre;
            degreeBD.CreationDate=DateTime.Today;

            _context.Degrees.Add(degreeBD);
            _context.SaveChanges();
         
            return Redirect("DegreeList");
        }   

        public IActionResult DegreeList()
    {
        /*Seccion de listado de carrera*/
        _logger.LogInformation("Esto es un mensaje al cargar las carreras");
         //Crear objeto de carrera
         DegreeModel Carrera=new DegreeModel();  
        Carrera.Nombre="Ingenieria en Tecnologias de la información";

         DegreeModel Carrera2=new DegreeModel();  
        Carrera2.Nombre="Licenciatura en administracion de empresas";

         DegreeModel Carrera3=new DegreeModel();  
        Carrera3.Nombre="Licenciatura en Contabilidad"; 

         //objeto de lista de carreras
         List<DegreeModel>list=new List<DegreeModel>(); 
        list.Add(Carrera);
        list.Add(Carrera2);
        list.Add(Carrera3);

        return View(list);
    }

          public IActionResult DegreeEdit(Guid Id)
    {
            DegreeModel carrera=new DegreeModel();  
           carrera.Id=Id;
            carrera.Nombre="Carrera cargada";
            return View(carrera);
    }

        [HttpPost]
        public IActionResult DegreeEdit(DegreeModel carrera)
        {
             if(!ModelState.IsValid)
           {
            _logger.LogWarning("El objeto no es valido");
            carrera.Nombre="Carrera no es valida";
            return View(carrera);
           }

            _logger.LogInformation("El objeto es valido");
         
            return Redirect("DegreeList");
 
        }

         public IActionResult DegreeShowToDelete(Guid Id)
         {
            //con el id se buscara en la base de datos el registro correspondiente
            //despues se le asigna al objeto
             DegreeModel carrera=new DegreeModel();  
            carrera.Id=Id;
            carrera.Nombre="Carrera para borrar";
            return View(carrera);
            
         }

          public IActionResult DegreeDeleted()
          {
            /*Borra el registro*/
            return Redirect ("DegreeList");
          }

    }

  
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFirstProyectWithLineCommand</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyFirstProyectWithLineCommand.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Prinicpal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Politicas de privacidad</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alumnos" asp-action="StudentList">Listado de Alumnos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="profes" asp-action="ListaProfesores">Listado de Maestros</a>
                        </li>
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Degree" asp-action="DegreeList">Listado de Carreras</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MyFirstProyectWithLineCommand - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>