Controllers/ProfesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyFirstProyectWithLineCommand.Models;

namespace MyFirstProyectWithLineCommand.Controllers

{
    public class ProfesController : Controller
    
    {
         private readonly ILogger<ProfesController> _logger;
        public ProfesController(ILogger<ProfesController> logger)
        {
             _logger = logger;
        }
      

       public IActionResult ProfesAdd()
        {
            return View();  
        }  

         [HttpPost]
         public IActionResult ProfesAdd(ProfeModel profes)
        {
           if(!ModelState.IsValid)
           {
            _logger.LogWarning("El objeto no es valido");
            return View();
           }

            _logger.LogInformation("El objeto es valido");
         
            return Redirect("ListaProfesores");
        }  

           public IActionResult ListaProfesores()
    {
        /*seccion de listado de profes*/
         //_logger.LogInformation("Esto es un mensaje al cargar los profesores");
        
        //CREAR OBJETOS PROFES
        ProfeModel profe=new ProfeModel();
        profe.Nombre="Ricardo Elizalde";
        profe.Carrera="POO2";
        profe.Sexo="Masculino";
        

        ProfeModel profe2=new ProfeModel();
        profe2.Nombre="Pablo Chapa";
         profe2.Carrera="IDAE";
        profe2.Sexo="Masculino";
        

       

        ProfeModel profe3=new ProfeModel();
        profe3.Nombre="Javier Lara";
         profe3.Carrera="Cálculo integral".ToUpper();
        profe3.Sexo="Masculino";
        
        ProfeModel profe4=new ProfeModel();
        profe4.Nombre="Cesar Caballero";
         profe4.Carrera="Fundamentos de programación".ToUpper();
        profe4.Sexo="Masculino";

       //OBJETO DE LISTA DE PROFES
       List<ProfeModel>list=new List<ProfeModel>();    
        list.Add(profe);
        list.Add(profe2);
        list.Add(profe3);
        list.Add(profe4);

        

        return View(list);
    }

          public IActionResult ProfesSave()
        {
            /*
                Guardar info de profes
            */

            return Redirect("ListaProfesores");
        }   

        public IActionResult ProfeShowAndEdit(Guid Id)   
        {
            ProfeModel profe= new ProfeModel();
            profe.Id=Id;   
            profe.Nombre="Profesor cargado"; 
            return View(profe);  
        }

        public IActionResult ProfesEdit(Guid Id)
        {
             ProfeModel Docente=new ProfeModel();  
           Docente.Id=new Guid();
            Docente.Nombre="profe agregado";
            return View(Docente);
        }


             [HttpPost]
                 public IActionResult ProfesEdit(ProfeModel maestro)
        {
             if(!ModelState.IsValid)
           {
            _logger.LogWarning("El objeto no es valido");
            maestro.Nombre="Maestro no es valido";
            return View(maestro);
           }

            _logger.LogInformation("El objeto es valido");
         
            return Redirect("DegreeList");
           

           
        }




        public IActionResult ProfeShowToDelete(Guid Id)
        {

            //Con el id se buscara en la base de datos 
            //despues se le asignara al objeto
              ProfeModel profe= new ProfeModel();
            profe.Id=Id;   
            profe.Nombre="Profe para borrar"; 
            return View(profe); 
           
        }
         public IActionResult profesDeleted()
         {
            /*Borrar el registro*/

            return Redirect("ListaProfesores");
         }
       
    }
    
   

}

Views/profes/ListaProfesores.cshtml
@model IEnumerable<ProfeModel>;

@{
    ViewData["Title"] = "Listado de Profesores";

    DateTime hoy=new DateTime(2024,05,17);
}

<div class="text-center">
<h2>@DateTime.Now </h2>



   <h1 class="display-2">Listado de Maestros</h1>
 <img src="~/imagenes/profesor.jpg" width="200" height="200"><br><br>


<a asp-controller="profes" asp-action="ProfesAdd"
class="btn btn-primary mb-3">
    Agregar Profesor
</a>
</div>


<table class="table">
    <thead>
        <tr>
            <th>Acciones</th>
            <th>Nombre</th>
            <th>Materia que imparte</th>
            <th>Sexo</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var profe in Model)
        {
            <tr>
                <td>
                    <a class="btn btn-primary" asp-controller="Profes"
                     asp-action="ProfesEdit" asp-route-id="@profe.Id">Editar</a>

                      <a class="btn btn-danger" asp-controller="Profes"
                     asp-action="ProfeShowToDelete" asp-route-id="@profe.Id">Borrar</a>
                </td>
                <td>
                    @profe.Nombre
                </td>
                 <td>
                    @profe.Carrera
                </td>
                 <td>
                    @profe.Sexo
                </td>



            </tr>
        }

    </tbody>

    <tfoot>

    </tfoot>
    
</table>

Views/profes/ProfeShowAndEdit.cshtml
@model ProfeModel; 

@{
    ViewData["Title"] = "Editar Lista de Profesores";

}
<div class="text-center">  
    <h1 class="display-2">Editar datos del Maestro: @Model.Nombre</h1>
</div>

<form asp-asp-controller="profes" asp-action="ProfesEdit">

<div class="mb-3">
        <label for="nombre" class="form-label">Nombre</label>
        <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Escriba el Nombre" />
</div>

<button type ="submit" class="btn btn-primary"> Guardar</button>

<a asp-controller="profes" asp-action="ListaProfesores"
class="btn btn-secundary mb-3">
    Regresar
</a>
</form>

Views/profes/ProfeShowToDelete.cshtml
@model ProfeModel;

@{
    ViewData["Title"] = "Borrar al profesor";

}
<div class="mb-3">  
 ¿Esta seguro que desea eliminar al maestro: @Model.Nombre ?
</div>

<form asp-controller="profes" asp-action="profesDeleted">
    <button type="submit" class="btn btn-danger">Borrar</button>
    <a class="btn btn-secundary" asp-action="ListaProfesores" asp-controller="profes">
        Regresar
    </a>

</form>

Views/profes/ProfesAdd.cshtml
@{
    ViewData["Title"] = "Alta de Profesores";

}
<div class="text-center">  
    <h1 class="display-2">Alta de maestro</h1>
</div>

 <div asp-validation-summary="All" class="text-danger"></div>
<form asp-asp-controller="profes" asp-action="ProfesAdd">

<div class="mb-3">
        <label for="nombre" class="form-label">Nombre</label>
        <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Escriba el Nombre" />

</div>
<div class="mb-3">
        <label for="matricula" class="form-label">Materia que imparte</label>
        <input type="text" class="form-control" id="carrera" name="carrera" placeholder="Escriba la Materia" />
</div>

<div class="mb-3">
        <label for="matricula" class="form-label">Sexo</label>
        <input type="text" class="form-control" id="sexo" name="sexo" placeholder="Escriba el genero" />
</div>

<button type ="submit" class="btn btn-primary"> Guardar</button>

<a asp-controller="profes" asp-action="ListaProfesores"
class="btn btn-secundary mb-3">
    Regresar
</a>
</form>

Views/profes/ProfesEdit.cshtml
@model ProfeModel; 

@{
    ViewData["Title"] = "Editar Lista de Profesores";

}
<div class="text-center">  
    <h1 class="display-2">Editar datos del Maestro: @Model.Nombre</h1>
</div>

<div asp-validation-summary="All" class="text-danger"></div>
<form asp-controller="profes" asp-action="ProfesEdit">

<div class="mb-3">
        <label for="nombre" class="form-label">Nombre</label>
        <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Escriba el Nombre" />
</div>
<div class="mb-3">
        <label for="matricula" class="form-label">Materia que imparte</label>
        <input type="text" class="form-control" id="carrera" name="carrera" placeholder="Escriba la Materia" />
</div>
<div class="mb-3">
        <label for="matricula" class="form-label">Sexo</label>
        <input type="text" class="form-control" id="sexo" name="sexo" placeholder="Escriba el genero" />
</div>



<button type ="submit" class="btn btn-primary"> Guardar</button>

<a asp-controller="profes" asp-action="ListaProfesores"
class="btn btn-secundary mb-3">
    Regresar
</a>
</form>